/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.GestionBuses;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Bus;
import model.DocumentoHasBus;

/**
 *
 * @author ESTIBENSON MAESTRE
 */
public class DocumentosBus extends javax.swing.JFrame {

    Gestionar_buses buses;
    Object[] opcionesEliminarBus = {"Si, Eliminar Documento", "No, Cancelar"};
    private EntityManagerFactory emf;
    private EntityManager em;
    private EntityTransaction tx;
    private Bus bus;
    List<DocumentoHasBus> listaDocs;
    DefaultTableModel model;

    public DocumentosBus(EntityManagerFactory emf, EntityManager em, EntityTransaction tx, Bus bus) {
        this.emf = emf;
        this.em = em;
        this.tx = tx;
        this.bus = bus;
        initComponents();
        this.setLocationRelativeTo(null);

        int idBus = bus.getIdBus();

        listaDocs = bus.getDocumentoHasBusList();

        Object[] columnNames = {"Tipo", "Numero", "Fecha de Expedición", "Fecha de Expiración",};
        model = new DefaultTableModel(new Object[0][0], columnNames);
        for (DocumentoHasBus listaDoc : listaDocs) {
            Object[] o = new Object[4];
            o[0] = listaDoc.getDocumento().getNombre();
            o[1] = listaDoc.getDocumento().getIdDocumento();
            o[2] = listaDoc.getFechaExpedicion();
            o[3] = listaDoc.getFechaExpiracion();
            model.addRow(o);
        }
        tablaDocs.setModel(model);

    }

    /**
     * Creates new form Documentos
     */
    public DocumentosBus() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDocs = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFechaExpedicion = new com.toedter.calendar.JDateChooser();
        txtFechaExpiracion = new com.toedter.calendar.JDateChooser();
        btnGestBusSalirDocumentos = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        setTitle("Documentos Bus");

        tablaDocs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "tipo_documento", "numero", "Fecha Expiracionn", "Fecha de expedicion"
            }
        ));
        jScrollPane1.setViewportView(tablaDocs);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel3.setText("Fecha de expiración:");

        jLabel4.setText("Fecha de expedición:");

        btnGestBusSalirDocumentos.setBackground(new java.awt.Color(0, 204, 255));
        btnGestBusSalirDocumentos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestBusSalirDocumentos.setText("Salir");
        btnGestBusSalirDocumentos.setBorder(null);
        btnGestBusSalirDocumentos.setBorderPainted(false);
        btnGestBusSalirDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestBusSalirDocumentosActionPerformed(evt);
            }
        });

        btnGuardarCambios.setBackground(new java.awt.Color(0, 204, 255));
        btnGuardarCambios.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.setBorder(null);
        btnGuardarCambios.setBorderPainted(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(404, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(btnGestBusSalirDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestBusSalirDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestBusSalirDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestBusSalirDocumentosActionPerformed
        buses = new Gestionar_buses();
        buses.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGestBusSalirDocumentosActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        
        if (txtFechaExpedicion.getDate() == null || txtFechaExpiracion.getDate() == null) {
                        JOptionPane.showMessageDialog(this, "Debe llenar todos los campos fechas para guardar cambios.", "Campos vacíos", JOptionPane.ERROR_MESSAGE);           

        } 
        
        int n = JOptionPane.showOptionDialog(this, "Seguro desea guardar cambios?", "Guardar cambios", JOptionPane.YES_NO_CANCEL_OPTION, WIDTH, null, opcionesEliminarBus, opcionesEliminarBus[1]);
        if (n == 0) {
            // guardar cambios
            JOptionPane.showMessageDialog(this, "Documento guardado exitosamente");

        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestBusSalirDocumentos;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaDocs;
    private com.toedter.calendar.JDateChooser txtFechaExpedicion;
    private com.toedter.calendar.JDateChooser txtFechaExpiracion;
    // End of variables declaration//GEN-END:variables
}
