package vista.GestiondeRutas;

import static java.awt.image.ImageObserver.WIDTH;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Ruta;

/**
 *
 * @author ESTIBENSON MAESTRE
 */
public class GestionRutas extends javax.swing.JFrame {

    Object[] opcionesEliminarRuta = {"Si, Eliminar Ruta","No, Cancelar"};
    private EntityManagerFactory emf;
    private EntityManager em;
    private EntityTransaction tx;
    List<Ruta> rutas;
    /**
     * Creates new form GestionRutas
     */
    public GestionRutas() {
        emf = Persistence.createEntityManagerFactory("TransvallePU");
        em = emf.createEntityManager();
        tx = em.getTransaction();
        initComponents();
        this.setLocationRelativeTo(null);        
        
        rutas = em.createNamedQuery("Ruta.findAll").getResultList();

        Object[] columnNames = {"Nombre", "Planilla Control", "Capacidad", "Descripción", "Descripción Retorno", "Descripción Salida", "Frecuencia", "Gabela", "Longitud", "Tiempo Recorrido"};
        DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames);
        for (Ruta ruta : rutas) {
            Object[] o = new Object[12];
            o[0] = ruta.getNombre();
            o[1] = ruta.getPlanillaControl();
            o[2] = ruta.getCapacidad();
            o[3] = ruta.getDescripcion();
            o[4] = ruta.getDescripcionRetorno();
            o[5] = ruta.getDescripcionSalida();
            o[6] = ruta.getFrecuencia();
            o[7] = ruta.getGabela();
            o[8] = ruta.getLongitud();
            o[9] = ruta.getTiempoRecorrido();
            model.addRow(o);
        }
        tablaRutaPrincipal.setModel(model);
        
        tablaRutaPrincipal.getColumn(columnNames[1]).setPreferredWidth(150);
        tablaRutaPrincipal.getColumn(columnNames[9]).setPreferredWidth(150);
        tablaRutaPrincipal.getColumn(columnNames[4]).setPreferredWidth(200);
        tablaRutaPrincipal.getColumn(columnNames[5]).setPreferredWidth(200);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRutaIrAgregar = new javax.swing.JButton();
        btnRutaSalir = new javax.swing.JButton();
        btnRutaIrAConsultarRuta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        btnRutaEliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaRutaPrincipal = new javax.swing.JTable();
        btnRutaIrAEditar = new javax.swing.JButton();

        setTitle("Gestión de Rutas");

        btnRutaIrAgregar.setBackground(new java.awt.Color(0, 204, 255));
        btnRutaIrAgregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRutaIrAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnRutaIrAgregar.setText("Agregar Ruta");
        btnRutaIrAgregar.setBorder(null);
        btnRutaIrAgregar.setBorderPainted(false);
        btnRutaIrAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutaIrAgregar.setFocusPainted(false);
        btnRutaIrAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaIrAgregarActionPerformed(evt);
            }
        });

        btnRutaSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnRutaSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRutaSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnRutaSalir.setText("Salir");
        btnRutaSalir.setBorder(null);
        btnRutaSalir.setBorderPainted(false);
        btnRutaSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutaSalir.setFocusPainted(false);
        btnRutaSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaSalirActionPerformed(evt);
            }
        });

        btnRutaIrAConsultarRuta.setBackground(new java.awt.Color(0, 204, 255));
        btnRutaIrAConsultarRuta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRutaIrAConsultarRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnRutaIrAConsultarRuta.setText("Consultar Rutas");
        btnRutaIrAConsultarRuta.setBorder(null);
        btnRutaIrAConsultarRuta.setBorderPainted(false);
        btnRutaIrAConsultarRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutaIrAConsultarRuta.setFocusPainted(false);
        btnRutaIrAConsultarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaIrAConsultarRutaActionPerformed(evt);
            }
        });

        jButton4.setText("Buscar ");

        jLabel1.setText("Insertar valor a Buscar:");

        jRadioButton1.setText("Vial");

        jRadioButton2.setText("Ruta");

        btnRutaEliminar.setBackground(new java.awt.Color(0, 204, 255));
        btnRutaEliminar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRutaEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnRutaEliminar.setText("Eliminar Ruta");
        btnRutaEliminar.setBorder(null);
        btnRutaEliminar.setBorderPainted(false);
        btnRutaEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutaEliminar.setFocusPainted(false);
        btnRutaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaEliminarActionPerformed(evt);
            }
        });

        tablaRutaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaRutaPrincipal.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaRutaPrincipal.setRowHeight(26);
        jScrollPane3.setViewportView(tablaRutaPrincipal);
        if (tablaRutaPrincipal.getColumnModel().getColumnCount() > 0) {
            tablaRutaPrincipal.getColumnModel().getColumn(0).setPreferredWidth(120);
            tablaRutaPrincipal.getColumnModel().getColumn(1).setResizable(false);
            tablaRutaPrincipal.getColumnModel().getColumn(1).setPreferredWidth(120);
            tablaRutaPrincipal.getColumnModel().getColumn(2).setResizable(false);
            tablaRutaPrincipal.getColumnModel().getColumn(2).setPreferredWidth(120);
            tablaRutaPrincipal.getColumnModel().getColumn(3).setResizable(false);
            tablaRutaPrincipal.getColumnModel().getColumn(3).setPreferredWidth(120);
        }

        btnRutaIrAEditar.setBackground(new java.awt.Color(0, 204, 255));
        btnRutaIrAEditar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRutaIrAEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnRutaIrAEditar.setText("Editar Rutas");
        btnRutaIrAEditar.setBorder(null);
        btnRutaIrAEditar.setBorderPainted(false);
        btnRutaIrAEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRutaIrAEditar.setFocusPainted(false);
        btnRutaIrAEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaIrAEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton2)
                        .addGap(59, 59, 59)
                        .addComponent(jRadioButton1)
                        .addGap(57, 57, 57)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRutaIrAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRutaIrAConsultarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(btnRutaIrAEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnRutaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81)
                            .addComponent(btnRutaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton1)
                        .addComponent(jRadioButton2)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRutaIrAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutaSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutaIrAConsultarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRutaIrAEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRutaIrAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaIrAgregarActionPerformed
        RegistroRuta rutas = new RegistroRuta(em, tx);
        rutas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRutaIrAgregarActionPerformed

    private void btnRutaIrAConsultarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaIrAConsultarRutaActionPerformed
        int row = tablaRutaPrincipal.getSelectedRow();
        if (row != -1) {    //fila seleccionada
            Ruta p = rutas.get(row);
            DetalleRuta detalle = new DetalleRuta(p);
            detalle.setVisible(true);
        }else { // no se selecciono ninguna fila
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una ruta.", "Ninguna ruta seleccionada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRutaIrAConsultarRutaActionPerformed

    private void btnRutaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaEliminarActionPerformed

int row = tablaRutaPrincipal.getSelectedRow();

        if (row != -1) {    //fila seleccionada
            Ruta p = rutas.get(row);
            int n = JOptionPane.showOptionDialog(this, "Seguro desea eliminar la Ruta?", "Eliminar Ruta", JOptionPane.YES_NO_CANCEL_OPTION, WIDTH, null, opcionesEliminarRuta, opcionesEliminarRuta[1]);
            if (n == 0) {
                // eliminar bus           
                tx.begin();
                em.remove(em.merge(p));
                tx.commit();
                JOptionPane.showMessageDialog(this, "Ruta eliminada exitosamente");
            }
        } else { // no se selecciono ninguna fila
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una ruta para eliminar.", "Ninguna ruta seleccionada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRutaEliminarActionPerformed

    private void btnRutaSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRutaSalirActionPerformed

    private void btnRutaIrAEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaIrAEditarActionPerformed
        int row = tablaRutaPrincipal.getSelectedRow();

        if (row != -1) {    //fila seleccionada
            Ruta p = rutas.get(row);
            RegistroRuta edtrutas = new RegistroRuta(em, tx, p);
            edtrutas.setVisible(true);
            this.setVisible(false);
        } else { // no se selecciono ninguna fila
            JOptionPane.showMessageDialog(this, "Debe Seleccionar una ruta para editar.", "Ninguna ruta seleccionada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRutaIrAEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRutaEliminar;
    private javax.swing.JButton btnRutaIrAConsultarRuta;
    private javax.swing.JButton btnRutaIrAEditar;
    private javax.swing.JButton btnRutaIrAgregar;
    private javax.swing.JButton btnRutaSalir;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaRutaPrincipal;
    // End of variables declaration//GEN-END:variables
}
